# coding: utf-8
###
# @file   identical.py
# @author Sébastien Rouault <sebastien.rouault@alumni.epfl.ch>
#
# @section LICENSE
#
# Copyright © 2018-2021 École Polytechnique Fédérale de Lausanne (EPFL).
# See LICENSE file.
#
# @section DESCRIPTION
#
# Collection of attacks which submit f identical gradients, which consist in
# adding as much of one attack vector to the average of the honest gradients.
#
# These attacks have been introduced in/adapted from the following papers:
# bulyan · El Mhamdi El Mahdi, Guerraoui Rachid, and Rouault Sébastien.
#          The Hidden Vulnerability of Distributed Learning in Byzantium.
#          ICML 2018. URL: http://proceedings.mlr.press/v80/mhamdi18a.html
# empire · Cong Xie, Oluwasanmi Koyejo, Indranil Gupta.
#          Fall of Empires: Breaking Byzantine-tolerant SGD by Inner Product Manipulation.
#          UAI 2019. URL: http://auai.org/uai2019/proceedings/papers/83.pdf
# little · Moran Baruch, Gilad Baruch, Yoav Goldberg.
#          A Little Is Enough: Circumventing Defenses For Distributed Learning.
#          2019 Feb 16. ArXiv. URL: https://arxiv.org/pdf/1902.06156v1
###

"""
Identical-gradient Byzantine attacks.

These attacks generate ``f_real`` references to the same newly created
Byzantine gradient. The gradient is built from the average honest gradient plus
a scaled attack direction.

Available attack directions are:

1. **Bulyan**: unit vector, optionally restricted to one coordinate.
2. **Empire**: negative average honest gradient.
3. **Little**: coordinate-wise standard deviation of honest gradients.

Parameters
----------
factor : float or int, optional
    Attack scaling factor. Positive values use the provided factor directly.
    Negative integers trigger a line search over ``-factor`` evaluations.
    Defaults to ``-16``.
negative : bool, optional
    Whether to negate the selected factor. Defaults to ``False``.

Notes
-----
The returned list may contain repeated references to the same Byzantine tensor,
which is allowed by the attack contract for identical-gradient attacks. The
tensor itself is newly created and does not alias any honest input gradient.

Example
-------

>>> import torch
>>> from aggregators import average
>>> from attacks import little
>>> grad_honests = [torch.tensor([1., 2., 3.]), torch.tensor([4., 5., 6.])]
>>> byzantine_grads = little(
...     grad_honests=grad_honests,
...     f_decl=1,
...     f_real=1,
...     defense=average,
...     model=None,
...     factor=1.5,
... )
>>> len(byzantine_grads)
1
"""

import math

import torch

import tools

from . import register

# ---------------------------------------------------------------------------- #
# Generic attack implementation generator


def make_attack(compute_direction):
    """
    Create an identical-gradient attack from a direction function.

    Parameters
    ----------
    compute_direction : callable
        Function computing the attack direction from stacked honest gradients and
        their average.

    Returns
    -------
    callable
        Attack function compatible with the attack registration contract.
    """

    def attack(
        grad_honests,
        f_real,
        f_decl,
        defense,
        model,
        factor=-16,
        negative=False,
        **kwargs,
    ):
        """
        Generate identical Byzantine gradients.

        Parameters
        ----------
        grad_honests : list of torch.Tensor
            Non-empty list of honest gradients.
        f_real : int
            Number of Byzantine gradients to generate.
        f_decl : int
            Number of declared Byzantine gradients passed to ``defense``.
        defense : callable
            Aggregation rule to defeat.
        model : torch.nn.Module
            Model forwarded to ``defense``.
        factor : float or int, optional
            Attack factor. Positive values are used directly; negative integers
            trigger automatic factor optimization.
        negative : bool, optional
            Whether to negate the selected factor. Defaults to ``False``.
        **kwargs : object
            Additional keyword arguments forwarded to ``compute_direction``.

        Returns
        -------
        list of torch.Tensor
            Generated Byzantine gradients. Each entry references the same newly
            created Byzantine tensor and does not alias any honest input
            gradient.
        """
        # Fast path
        if f_real == 0:
            return list()
        # Stack and compute the average honest gradient, and then the attack vector
        grad_stck = torch.stack(grad_honests)
        grad_avg = grad_stck.mean(dim=0)
        grad_att = compute_direction(grad_stck, grad_avg, **kwargs)
        # Evaluate the best attack factor (if required)
        if factor < 0:

            def eval_factor(factor):
                # Apply the given factor
                if negative:
                    factor = -factor
                grad_attack = grad_avg + factor * grad_att
                # Measure effective squared distance
                aggregated = defense(
                    gradients=(grad_honests + [grad_attack] * f_real),
                    f=f_decl,
                    model=model,
                )
                aggregated.sub_(grad_avg)
                return aggregated.dot(aggregated).item()

            factor = tools.line_maximize(eval_factor, evals=math.ceil(-factor))
        else:
            if negative:
                factor = -factor
        # Generate the Byzantine gradient from the given/computed factor
        byz_grad = grad_avg
        grad_att.mul_(factor)
        byz_grad.add_(grad_att)
        # Return this Byzantine gradient 'f_real' times
        return [byz_grad] * f_real

    # Return the attack closure
    return attack


def check(grad_honests, f_real, defense, factor=-16, negative=False, **kwargs):
    """
    Check parameter validity for identical-gradient attacks.

    Parameters
    ----------
    grad_honests : list
        Non-empty list of honest gradients.
    f_real : int
        Number of Byzantine gradients to generate.
    defense : callable
        Aggregation rule to defeat.
    factor : float or int, optional
        Attack factor. Defaults to ``-16``.
    negative : bool, optional
        Whether to negate the selected factor. Defaults to ``False``.
    **kwargs : object
        Additional keyword arguments, ignored by this check.

    Returns
    -------
    str or None
        ``None`` when parameters are valid, otherwise a user-facing error
        message.
    """
    if not isinstance(grad_honests, list) or len(grad_honests) == 0:
        return "Expected a non-empty list of honest gradients, got %r" % (grad_honests,)
    if not isinstance(f_real, int) or f_real < 0:
        return (
            "Expected a non-negative number of Byzantine gradients to generate, got %r"
            % (f_real,)
        )
    if not callable(defense):
        return "Expected a callable for the aggregation rule, got %r" % (defense,)
    if not (
        (isinstance(factor, float) and factor > 0)
        or (isinstance(factor, int) and factor != 0)
    ):
        return (
            "Expected a positive number or a negative integer for the attack factor, got %r"
            % (factor,)
        )
    if not isinstance(negative, bool):
        return "Expected a boolean for optional parameter 'negative', got %r" % (
            negative,
        )


# ---------------------------------------------------------------------------- #
# Attack vector computations


def bulyan(grad_stck, grad_avg, target_idx=-1, **kwargs):
    """
    Compute the Bulyan attack direction.

    This direction is adapted from "The Hidden Vulnerability of Distributed
    Learning in Byzantium".

    Parameters
    ----------
    grad_stck : torch.Tensor
        Stacked honest gradients.
    grad_avg : torch.Tensor
        Average honest gradient.
    target_idx : int or str, optional
        Targeted coordinate index, or ``"all"`` to target every coordinate.
        Defaults to ``-1``.
    **kwargs : object
        Additional keyword arguments, ignored by this direction.

    Returns
    -------
    torch.Tensor
        Attack direction.
    """
    if target_idx == "all":
        return torch.ones_like(grad_avg)
    else:
        assert isinstance(target_idx, int), (
            "Expected an integer or \"all\" for 'target_idx', got %r" % (target_idx,)
        )
        grad_att = torch.zeros_like(grad_avg)
        grad_att[target_idx] = 1
        return grad_att


def empire(grad_stck, grad_avg, **kwargs):
    """
    Compute the Empire attack direction.

    This direction is adapted from "Fall of Empires".

    Parameters
    ----------
    grad_stck : torch.Tensor
        Stacked honest gradients.
    grad_avg : torch.Tensor
        Average honest gradient.
    **kwargs : object
        Additional keyword arguments, ignored by this direction.

    Returns
    -------
    torch.Tensor
        Attack direction, equal to the negative average honest gradient.
    """
    return grad_avg.neg()


def little(grad_stck, grad_avg, **kwargs):
    """
    Compute the Little attack direction.

    This direction is adapted from "A Little Is Enough".

    Parameters
    ----------
    grad_stck : torch.Tensor
        Stacked honest gradients.
    grad_avg : torch.Tensor
        Average honest gradient.
    **kwargs : object
        Additional keyword arguments, ignored by this direction.

    Returns
    -------
    torch.Tensor
        Attack direction, computed as the coordinate-wise standard deviation of
        honest gradients.
    """
    return grad_stck.var(dim=0).sqrt_()


# ---------------------------------------------------------------------------- #
# Attack registrations

# Register the attacks
for name, func in (("bulyan", bulyan), ("empire", empire), ("little", little)):
    register(name, make_attack(func), check)
