# coding: utf-8
###
 # @file   identical.py
 # @author Sébastien Rouault <sebastien.rouault@alumni.epfl.ch>
 #
 # @section LICENSE
 #
 # Copyright © 2018-2021 École Polytechnique Fédérale de Lausanne (EPFL).
 # See LICENSE file.
 #
 # @section DESCRIPTION
 #
 # Collection of attacks which submit f identical gradients, which consist in
 # adding as much of one attack vector to the average of the honest gradients.
 #
 # These attacks have been introduced in/adapted from the following papers:
 # bulyan · El Mhamdi El Mahdi, Guerraoui Rachid, and Rouault Sébastien.
 #          The Hidden Vulnerability of Distributed Learning in Byzantium.
 #          ICML 2018. URL: http://proceedings.mlr.press/v80/mhamdi18a.html
 # empire · Cong Xie, Oluwasanmi Koyejo, Indranil Gupta.
 #          Fall of Empires: Breaking Byzantine-tolerant SGD by Inner Product Manipulation.
 #          UAI 2019. URL: http://auai.org/uai2019/proceedings/papers/83.pdf
 # little · Moran Baruch, Gilad Baruch, Yoav Goldberg.
 #          A Little Is Enough: Circumventing Defenses For Distributed Learning.
 #          2019 Feb 16. ArXiv. URL: https://arxiv.org/pdf/1902.06156v1
###

"""
This attack generates multiple copies of the same Byzantine gradient. The attack
vector is computed based on the honest gradients and added to their average
with a specific factor.

Three attack directions are available:

1. **Bulyan**: Uses a vector of ones (or single coordinate) as attack direction
2. **Empire**: Uses the negative of the average gradient
3. **Little**: Uses the standard deviation of gradients as attack direction

Parameters
----------

factor : float or int, optional
    Attack scaling factor. Positive values add the attack vector, negative values
    trigger automatic optimization to find the best factor. Default is -16 (evaluates
    up to 16 factors to find optimal).
negative : bool, optional
    Whether to use negative factor. Default is False.

Example
-------

>>> import torch
>>> from attacks import identical
>>> honest_grads = [torch.tensor([1., 2., 3.]), torch.tensor([4., 5., 6.])]
>>> byzantine_grads = identical.little(honest_grads=honest_grads, f_decl=1, f_real=1, model=None)
>>> print(byzantine_grads[0])
tensor([...])  # Modified gradient based on std dev
"""

import tools

import math
import torch

from . import register

# ---------------------------------------------------------------------------- #
# Generic attack implementation generator

def make_attack(compute_direction):
    """
    Create the attack gradient generation closure.

    Parameters
    ----------
    compute_direction : callable
        Attack vector computation function.

    Returns
    -------
    callable
        Attack gradient generation closure.
    """
    def attack(grad_honests, f_real, f_decl, defense, model, factor=-16, negative=False, **kwargs):
        """
        Generate the attack gradients.

        Parameters
        ----------
        grad_honests : list of torch.Tensor
            Non-empty list of honest gradients.
        f_decl : int
            Number of declared Byzantine gradients.
        f_real : int
            Number of Byzantine gradients to generate.
        defense : callable
            Aggregation rule in use to defeat.
        model : torch.nn.Module
            Model with valid default dataset and loss set.
        factor : float or int, optional
            Attack factor. Positive for fixed, negative for auto-optimization.
        negative : bool, optional
            Use negative factor. Default is False.
        **kwargs : dict
            Additional keyword arguments.

        Returns
        -------
        list of torch.Tensor
            Generated Byzantine gradients (all references to one).
        """
        # Fast path
        if f_real == 0:
            return list()
        # Stack and compute the average honest gradient, and then the attack vector
        grad_stck = torch.stack(grad_honests)
        grad_avg  = grad_stck.mean(dim=0)
        grad_att  = compute_direction(grad_stck, grad_avg, **kwargs)
        # Evaluate the best attack factor (if required)
        if factor < 0:
            def eval_factor(factor):
                # Apply the given factor
                if negative:
                    factor = -factor
                grad_attack = grad_avg + factor * grad_att
                # Measure effective squared distance
                aggregated = defense(gradients=(grad_honests + [grad_attack] * f_real), f=f_decl, model=model)
                aggregated.sub_(grad_avg)
                return aggregated.dot(aggregated).item()
            factor = tools.line_maximize(eval_factor, evals=math.ceil(-factor))
        else:
            if negative:
                factor = -factor
        # Generate the Byzantine gradient from the given/computed factor
        byz_grad = grad_avg
        grad_att.mul_(factor)
        byz_grad.add_(grad_att)
        # Return this Byzantine gradient 'f_real' times
        return [byz_grad] * f_real
    # Return the attack closure
    return attack

def check(grad_honests, f_real, defense, factor=-16, negative=False, **kwargs):
    """
    Check parameter validity for this attack template.

    Parameters
    ----------
    grad_honests : list
        Non-empty list of honest gradients.
    f_real : int
        Number of Byzantine gradients to generate.
    defense : callable
        Aggregation rule in use to defeat.
    factor : float or int, optional
        Attack factor. Default is -16.
    negative : bool, optional
        Use negative factor. Default is False.
    **kwargs : dict
        Additional keyword arguments (ignored).

    Returns
    -------
    None or str
        None if valid, otherwise error message string.
    """
    if not isinstance(grad_honests, list) or len(grad_honests) == 0:
        return "Expected a non-empty list of honest gradients, got %r" % (grad_honests,)
    if not isinstance(f_real, int) or f_real < 0:
        return "Expected a non-negative number of Byzantine gradients to generate, got %r" % (f_real,)
    if not callable(defense):
        return "Expected a callable for the aggregation rule, got %r" % (defense,)
    if not ((isinstance(factor, float) and factor > 0) or (isinstance(factor, int) and factor != 0)):
        return "Expected a positive number or a negative integer for the attack factor, got %r" % (factor,)
    if not isinstance(negative, bool):
        return "Expected a boolean for optional parameter 'negative', got %r" % (negative,)

# ---------------------------------------------------------------------------- #
# Attack vector computations

def bulyan(grad_stck, grad_avg, target_idx=-1, **kwargs):
    """
    Compute the attack vector adapted from "The Hidden Vulnerability".

    Parameters
    ----------
    grad_stck : torch.Tensor
        Stacked honest gradients.
    grad_avg : torch.Tensor
        Average of honest gradients.
    target_idx : int or str, optional
        Index of the targeted coordinate, "all" for all. Default is -1 (last coordinate).
    **kwargs : dict
        Additional keyword arguments (ignored).

    Returns
    -------
    torch.Tensor
        Attack vector.
    """
    if target_idx == "all":
        return torch.ones_like(grad_avg)
    else:
        assert isinstance(target_idx, int), "Expected an integer or \"all\" for 'target_idx', got %r" % (target_idx,)
        grad_att = torch.zeros_like(grad_avg)
        grad_att[target_idx] = 1
        return grad_att

def empire(grad_stck, grad_avg, **kwargs):
    """
    Compute the attack vector adapted from "Fall of Empires".

    Parameters
    ----------
    grad_stck : torch.Tensor
        Stacked honest gradients.
    grad_avg : torch.Tensor
        Average of honest gradients.
    **kwargs : dict
        Additional keyword arguments (ignored).

    Returns
    -------
    torch.Tensor
        Attack vector (negative of average).
    """
    return grad_avg.neg()

def little(grad_stck, grad_avg, **kwargs):
    """
    Compute the attack vector adapted from "A Little is Enough".

    Parameters
    ----------
    grad_stck : torch.Tensor
        Stacked honest gradients.
    grad_avg : torch.Tensor
        Average of honest gradients.
    **kwargs : dict
        Additional keyword arguments (ignored).

    Returns
    -------
    torch.Tensor
        Attack vector (square root of variance).
    """
    return grad_stck.var(dim=0).sqrt_()

# ---------------------------------------------------------------------------- #
# Attack registrations

# Register the attacks
for name, func in (("bulyan", bulyan), ("empire", empire), ("little", little)):
    register(name, make_attack(func), check)
