# coding: utf-8
###
# @file   nan.py
# @author Sébastien Rouault <sebastien.rouault@alumni.epfl.ch>
#
# @section LICENSE
#
# Copyright © 2018-2021 École Polytechnique Fédérale de Lausanne (EPFL).
# See LICENSE file.
#
# @section DESCRIPTION
#
# Attack that generates NaN gradient(s), hence the name.
###

"""
NaN-valued Byzantine gradient attack.

This attack generates gradients filled with NaN (Not a Number) values in order
to test whether an aggregation rule detects, rejects, or propagates non-finite
inputs.

Use Case
--------

Simple baseline attack for evaluating aggregation-rule robustness against
non-finite values.

Properties
----------

- Generates newly allocated gradients filled with NaN values.
- Reuses the same Byzantine tensor object for all returned gradients.
- Does not alias any honest input gradient.
- No parameters beyond gradient count.

Example
-------

>>> import torch
>>> from attacks import nan
>>> grad_honests = [torch.tensor([1., 2., 3.]), torch.tensor([4., 5., 6.])]
>>> byzantine_grads = nan(grad_honests=grad_honests, f_real=1)
>>> byzantine_grads[0]
tensor([nan, nan, nan])
"""

import math

import torch

from . import register

# ---------------------------------------------------------------------------- #
# Non-finite gradient attack


def attack(
    grad_honests: list[torch.Tensor], f_real: int, **kwargs
) -> list[torch.Tensor]:
    """
    Generate NaN-valued Byzantine gradients.

    Parameters
    ----------
    grad_honests : list of torch.Tensor
        Non-empty list of honest gradients. The first gradient is used as the
        shape, dtype, and device template for the generated Byzantine tensor.
    f_real : int
        Number of Byzantine gradients to generate.
    **kwargs : object
        Additional keyword arguments, ignored by this attack.

    Returns
    -------
    list of torch.Tensor
        List containing ``f_real`` references to the same newly allocated
        NaN-valued Byzantine tensor. The returned tensor does not alias any
        honest input gradient.
    """
    # Fast path
    if f_real == 0:
        return list()
    # Generate the non-finite Byzantine gradient
    byz_grad = torch.empty_like(grad_honests[0])
    byz_grad.copy_(torch.tensor((math.nan,), dtype=byz_grad.dtype))
    # Return this Byzantine gradient 'f_real' times
    return [byz_grad] * f_real


def check(grad_honests: list[torch.Tensor], f_real: int, **kwargs) -> str | None:
    """
    Check parameter validity for the NaN attack.

    Parameters
    ----------
    grad_honests : list of torch.Tensor
        Non-empty list of honest gradients.
    f_real : int
        Number of Byzantine gradients to generate.
    **kwargs : object
        Additional keyword arguments, ignored by this check.

    Returns
    -------
    str or None
        ``None`` when parameters are valid, otherwise a user-facing error
        message.
    """
    if not isinstance(grad_honests, list) or len(grad_honests) == 0:
        return "Expected a non-empty list of honest gradients, got %r" % (grad_honests,)
    if not isinstance(f_real, int) or f_real < 0:
        return (
            "Expected a non-negative number of Byzantine gradients to generate, got %r"
            % (f_real,)
        )


# ---------------------------------------------------------------------------- #
# Attack registering

# Register the attack
register("nan", attack, check)
